"""Initial Item table

Revision ID: 968b8270ca5a
Revises: 
Create Date: 2022-06-21 23:49:48.715637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '968b8270ca5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("type != 'CATEGORY' OR price IS NULL", name='category_price_is_null'),
    sa.CheckConstraint("type != 'OFFER' OR price IS NOT NULL", name='offer_price_is_not_null'),
    sa.CheckConstraint("type in ('OFFER', 'CATEGORY')", name='type_value_check'),
    sa.CheckConstraint('price >= 0', name='price_value_check'),
    sa.ForeignKeyConstraint(['parent_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_parent_id'), 'items', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_parent_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
